<h2>Potential Talents: NLP Project

In [15]:
from pathlib import Path
PROJ_ROOT = Path().resolve().parents[0]
DATA_DIR = PROJ_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
RAW_DATA_PATH = RAW_DATA_DIR / "potential-talents - Aspiring human resources - seeking human resources.csv"

In [16]:
import pandas as pd

In [17]:
data = pd.read_csv(RAW_DATA_PATH)
data.head(5)

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,NaN
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,NaN
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,NaN
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,NaN
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,NaN

In [18]:
data.shape

(104, 5)

In [19]:
type(data["connection"][2])

str

In [20]:
# Remove duplicates, then rebuild a continuous id column
data = data.drop_duplicates(subset=["job_title", "location", "connection", "fit"]).reset_index(drop=True) #All id's are unique, but the info in the other columns (when combined), aren't
data["id"] = data.index + 1

data.shape

(53, 5)

In [21]:
print(data.loc[0, 'job_title'])

2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional

In terms of exploratory data analysis (EDA) the 'job_title' and 'location' features show high cardinality upon initial visual inspection. 'connection' and 'fit' will be the most useful in the case of EDA:

In [22]:
data.nunique()

id            53
job_title     52
location      41
connection    33
fit            0
dtype: int64

<h4>Steps Required to Create an NLP Recommender System:

1. Define the 'ideal' candidate via a new description or by 'starring' a candidate in the list.
2. Tokenize.
3. Compute the TF-IDF vectors. Converts the words into a high dimension vector.
4. Compute cosine similarity (0 - 1) between the 'ideal' candidate and the existing candidates.
5. Rank the cosine similarity.

In [23]:
# First we shall combine all the features (apart from 'id') into a single string to capture as much info as possible:
data["combined"] = (data["job_title"].astype(str)+ " located in " + data["location"].astype(str) + ", with " + data["connection"].astype(str)+ " connections."
)

# Test
data["combined"][0]

'2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional located in Houston, Texas, with 85 connections.'

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Next we transform the "combined" features into the input required for cosine similarity

data_by_id = data.set_index("id", drop=False)

# Tokenization + TF-IDF Vectorization:
tfidf_vectorizer = TfidfVectorizer(stop_words="english") # Carries out both tokenization and vectorization
tfidf_matrix = tfidf_vectorizer.fit_transform(data_by_id["combined"].fillna(""))

# Row order in tfidf_matrix matches data_by_id.index, making each vector traceable to its id
candidate_ids = data_by_id.index.to_numpy()

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Way to 'star' a candidate, then calculate cosine similarity.

def recommend_candidates_id(vectorizer,base_data,starred_id,top_n=10):
    """
    Recommends candidates based on similarity to a starred candidate by selecting the 'id' of the starred candidate.

    Use with TF-IDF model.
    """
    base = base_data.copy()

    if "combined" not in base.columns:
        required_cols = ["job_title", "location", "connection"]
        missing = [col for col in required_cols if col not in base.columns]
        if missing:
            raise ValueError(f"Missing required columns to build 'combined': {missing}")

        base["combined"] = (
            base["job_title"].astype(str)
            + " located in "
            + base["location"].astype(str)
            + ", with "
            + base["connection"].astype(str)
            + " connections."
        )

    if "id" in base.columns:
        base_by_id = base.set_index("id", drop=False)
    else:
        base_by_id = base.copy()

    if starred_id not in base_by_id.index:
        raise ValueError(f"id {starred_id} not found in base_data")

    matrix = vectorizer.fit_transform(base_by_id["combined"].fillna(""))

    starred_idx = base_by_id.index.get_loc(starred_id)
    scores = cosine_similarity(matrix[starred_idx], matrix).ravel()

    ranked = base_by_id.copy()
    ranked["fit"] = scores
    ranked = ranked[ranked["fit"] > 0].sort_values("fit", ascending=False)

    return ranked.head(top_n)

# example:
recommend_candidates_id(tfidf_vectorizer,data, 30, top_n=10)

,id,job_title,location,connection,fit,combined
id,,,,,,
30,30,Senior Human Resources Business Partner at Hei...,"Chattanooga, Tennessee Area",455,1.000000,Senior Human Resources Business Partner at Hei...
21,21,Business Management Major and Aspiring Human R...,"Monroe, Louisiana Area",5,0.168045,Business Management Major and Aspiring Human R...
8,8,HR Senior Specialist,San Francisco Bay Area,500+,0.161250,HR Senior Specialist located in San Francisco ...
22,22,"Aspiring Human Resources Manager, seeking inte...","Houston, Texas Area",7,0.128242,"Aspiring Human Resources Manager, seeking inte..."
51,51,Business Intelligence and Analytics at Travelers,Greater New York City Area,49,0.107094,Business Intelligence and Analytics at Travele...
1,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.100148,2019 C.T. Bauer College of Business Graduate (...
23,23,Human Resources Professional,Greater Boston Area,16,0.096722,Human Resources Professional located in Greate...
6,6,Aspiring Human Resources Specialist,Greater New York City Area,1,0.090369,Aspiring Human Resources Specialist located in...
46,46,Aspiring Human Resources Professional,"Kokomo, Indiana Area",71,0.088799,Aspiring Human Resources Professional located ...
13,13,Aspiring Human Resources Management student se...,"Houston, Texas Area",500+,0.084685,Aspiring Human Resources Management student se...

In [ ]:
# We could also use a description of an ideal candidate to act as the benchmark 'ideal' candidate:

ideal_candidate_description = "A business graduate"

def recommend_candidates_description(vectorizer,base_data, ideal_candidate_description, top_n=10):
    """
    Recommends candidates based on similarity to an ideal candidate description.
    Only non-zero cosine similarities are returned.

    Use with TF-IDF model.
    """
    if "id" in base_data.columns:
        base_by_id = base_data.set_index("id", drop=False)
    else:
        base_by_id = base_data.copy()

    matrix = vectorizer.fit_transform(base_by_id["combined"].fillna(""))
    ideal_vector = vectorizer.transform([ideal_candidate_description])

    scores = cosine_similarity(ideal_vector, matrix).ravel()

    ranked = base_by_id.copy()
    ranked["fit"] = scores
    ranked = ranked[ranked["fit"] > 0].sort_values("fit", ascending=False)

    return ranked.head(top_n)

tf_idf_ideal = recommend_candidates_description(tfidf_vectorizer,data_by_id, ideal_candidate_description)

In [36]:
tf_idf_ideal.head(10)

,id,job_title,location,connection,fit,combined
id,,,,,,
1,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.387305,2019 C.T. Bauer College of Business Graduate (...
21,21,Business Management Major and Aspiring Human R...,"Monroe, Louisiana Area",5,0.201242,Business Management Major and Aspiring Human R...
51,51,Business Intelligence and Analytics at Travelers,Greater New York City Area,49,0.167003,Business Intelligence and Analytics at Travele...
30,30,Senior Human Resources Business Partner at Hei...,"Chattanooga, Tennessee Area",455,0.158494,Senior Human Resources Business Partner at Hei...
45,45,Student at Indiana University Kokomo - Busines...,"Lafayette, Indiana",19,0.125188,Student at Indiana University Kokomo - Busines...

<h4>SentenceTransformers vs TF-IDF Vectorisation

In [29]:
from sentence_transformers import SentenceTransformer

c:\Users\cochr\Data Science Projects\RnEHGFbDNlguJZBv\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [32]:
st_model = SentenceTransformer('all-MiniLM-L6-v2') #Define which model to use

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9810.01it/s]

In [31]:
# Slightly different syntax when applying SentenceTransformers compared with TF-IDF model. New functions to use it:

In [37]:
def recommend_candidates_description_st(vectorizer,base_data, ideal_candidate_description, top_n=10):
    """
    Recommends candidates based on similarity to an ideal candidate description.
    Only non-zero cosine similarities are returned.

    Use with SentenceTransformers
    """
    if "id" in base_data.columns:
        base_by_id = base_data.set_index("id", drop=False)
    else:
        base_by_id = base_data.copy()

    candidate_descriptions = base_by_id["combined"].fillna("").tolist()
    candidate_vectors = vectorizer.encode(candidate_descriptions, convert_to_numpy=True)

    query_vector = vectorizer.encode([ideal_candidate_description])

    scores = cosine_similarity(query_vector, candidate_vectors).ravel()

    ranked = base_by_id.copy()
    ranked["fit"] = scores
    ranked = ranked[ranked["fit"] > 0].sort_values("fit", ascending=False)

    return ranked.head(top_n)

st_ideal = recommend_candidates_description_st(st_model,data_by_id, ideal_candidate_description)

In [39]:
print(ideal_candidate_description)

A business graduate

In [40]:
tf_idf_ideal.head(10) # TF-IDF

,id,job_title,location,connection,fit,combined
id,,,,,,
1,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.387305,2019 C.T. Bauer College of Business Graduate (...
21,21,Business Management Major and Aspiring Human R...,"Monroe, Louisiana Area",5,0.201242,Business Management Major and Aspiring Human R...
51,51,Business Intelligence and Analytics at Travelers,Greater New York City Area,49,0.167003,Business Intelligence and Analytics at Travele...
30,30,Senior Human Resources Business Partner at Hei...,"Chattanooga, Tennessee Area",455,0.158494,Senior Human Resources Business Partner at Hei...
45,45,Student at Indiana University Kokomo - Busines...,"Lafayette, Indiana",19,0.125188,Student at Indiana University Kokomo - Busines...

In [ ]:
st_ideal.head(10) # SentenceTransformers

,id,job_title,location,connection,fit,combined
id,,,,,,
1,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.466220,2019 C.T. Bauer College of Business Graduate (...
21,21,Business Management Major and Aspiring Human R...,"Monroe, Louisiana Area",5,0.459956,Business Management Major and Aspiring Human R...
28,28,Liberal Arts Major. Aspiring Human Resources A...,"Baton Rouge, Louisiana Area",7,0.451137,Liberal Arts Major. Aspiring Human Resources A...
45,45,Student at Indiana University Kokomo - Busines...,"Lafayette, Indiana",19,0.435448,Student at Indiana University Kokomo - Busines...
7,7,Student at Humber College and Aspiring Human R...,Kanada,61,0.421939,Student at Humber College and Aspiring Human R...
35,35,Information Systems Specialist and Programmer ...,"Gaithersburg, Maryland",4,0.408264,Information Systems Specialist and Programmer ...
15,15,Experienced Retail Manager and aspiring Human ...,"Austin, Texas Area",57,0.388252,Experienced Retail Manager and aspiring Human ...
8,8,HR Senior Specialist,San Francisco Bay Area,500+,0.369134,HR Senior Specialist located in San Francisco ...
6,6,Aspiring Human Resources Specialist,Greater New York City Area,1,0.363608,Aspiring Human Resources Specialist located in...
49,49,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,0.362337,Aspiring Human Resources Manager | Graduating ...

SentenceTransformer: It's giving relatively high scores to candidates which don't appear to fulfill the main characteristic of the ideal candidate...

TF-IDF appears to be better for this project.

Another test:

In [41]:
ideal_candidate_description = "Experienced in Human Resources"

In [42]:
tf_idf_ideal = recommend_candidates_description(tfidf_vectorizer,data_by_id, ideal_candidate_description) 
tf_idf_ideal.head(5) #TF-IDF

,id,job_title,location,connection,fit,combined
id,,,,,,
15,15,Experienced Retail Manager and aspiring Human ...,"Austin, Texas Area",57,0.475657,Experienced Retail Manager and aspiring Human ...
22,22,"Aspiring Human Resources Manager, seeking inte...","Houston, Texas Area",7,0.214073,"Aspiring Human Resources Manager, seeking inte..."
23,23,Human Resources Professional,Greater Boston Area,16,0.120795,Human Resources Professional located in Greate...
49,49,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,0.120654,Aspiring Human Resources Manager | Graduating ...
6,6,Aspiring Human Resources Specialist,Greater New York City Area,1,0.112862,Aspiring Human Resources Specialist located in...

In [43]:
st_ideal = recommend_candidates_description_st(st_model,data_by_id, ideal_candidate_description)
st_ideal.head(5) #ST

,id,job_title,location,connection,fit,combined
id,,,,,,
25,25,Aspiring Human Resources Professional | Passio...,"New York, New York",212,0.681822,Aspiring Human Resources Professional | Passio...
31,31,Aspiring Human Resources Professional | An ene...,"Austin, Texas Area",174,0.666754,Aspiring Human Resources Professional | An ene...
6,6,Aspiring Human Resources Specialist,Greater New York City Area,1,0.651478,Aspiring Human Resources Specialist located in...
3,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.638040,Aspiring Human Resources Professional located ...
49,49,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,0.631948,Aspiring Human Resources Manager | Graduating ...

Both models appear to be confusing 'experienced'. If candidate is experienced in anything, not necessarily HR specifically, it's assigned a high score. Even 'aspiring' is assigned a high score..

<h4>Additional Candidates

In [ ]:
# Define the base data set (in data/raw) as 'data'. Import the 'additional' data set csv as 'a_data', then add candidates
# and finally overwrite the csv file